services:
  shredder-admin:
    network_mode: host
    build:
      context: ..
      dockerfile: Dockerfile
    image: shredder-admin:v0.1
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../seed:/app/seed:ro
